[application]
# role: identifier for WindowManager (used in layers.json)
role = "browser"

# launch by "POSIX"(fork/exec), "AFM_DBUS"(afm via dbus),  "AFM_WEBSOCKET"(afm via websockt)
method = "POSIX"

# path: path to the executable
# e.g.
#   path = "/usr/bin/chromium"
path = "/usr/bin/app-shell/run_app_shell"

params = [
  "--folder /opt/enactbrowser",
  "--appid=enactbrowser",
]
